# Generated by Django 5.0.7 on 2024-08-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='著者名')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='色(16進数)')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='タイトル')),
                ('lead_text', models.TextField(blank=True, null=True, verbose_name='紹介文')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBNコード')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='出版年月日')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='更新日')),
                ('authors', models.ManyToManyField(to='book.author', verbose_name='著者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
